import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${geistSans.variable} ${geistMono.variable}`}>
                <header
                    style={{
                        padding: 16,
                        borderBottom: "1px solid #eee",
                        marginBottom: 20,
                    }}
                >
                    <div style={{ maxWidth: 640, margin: "0 auto" }}>
                        <strong>CSV Todo</strong>
                    </div>
                </header>
                <div style={{ padding: 20 }}>{children}</div>
            </body>
        </html>
    );
}
